# Generated by Django 2.0.3 on 2018-03-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('usernumber', models.BigIntegerField(max_length=9)),
                ('field', models.CharField(choices=[('EC', 'EC'), ('CE', 'CE'), ('EE', 'EE')], max_length=10)),
                ('avatar', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('posts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
            ],
        ),
    ]
