# Generated by Django 2.0.3 on 2018-03-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posts_id',
            new_name='PersonId',
        ),
    ]
