# Generated by Django 2.0.3 on 2018-03-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180309_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='field',
            field=models.CharField(choices=[('E', 'EC'), ('CE', 'CE'), ('EE', 'EE')], max_length=10),
        ),
    ]
