# Generated by Django 2.0.3 on 2018-03-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180309_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PersonId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
