# Generated by Django 2.0.3 on 2018-03-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180309_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='field',
            field=models.CharField(choices=[('EC', 'EC'), ('CE', 'CE'), ('EE', 'EE')], max_length=10),
        ),
    ]
