# Generated by Django 2.0.3 on 2018-03-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='flag',
            new_name='lflag',
        ),
    ]
