# Generated by Django 2.0.3 on 2018-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180309_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dflag',
            field=models.BooleanField(default=False),
        ),
    ]
