# Generated by Django 2.0.3 on 2018-03-09 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_dflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('postId', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
    ]
